services:
    Jfortunato\QuickBooksDesktopBundle\Config\Config:
        public: false
        arguments: ['%jfortunato_quick_books_desktop%', "@doctrine.dbal.default_connection"]

    jfortunato_quick_books_desktop.config:
        alias: Jfortunato\QuickBooksDesktopBundle\Config\Config
        public: true

    jfortunato_quick_books_desktop.factory.wrapper:
        class: Jfortunato\QuickBooksDesktopBundle\Factory\WrapperFactory
        arguments: ["@jfortunato_quick_books_desktop.config"]

    jfortunato_quick_books_desktop.wrapper.server:
        class: Jfortunato\QuickBooksDesktopBundle\Wrapper\Server
        factory: ["@jfortunato_quick_books_desktop.factory.wrapper", "newServer"]
        arguments: ["@jfortunato_quick_books_desktop.mapper"]

    jfortunato_quick_books_desktop.wrapper.utilities:
        class: Jfortunato\QuickBooksDesktopBundle\Wrapper\Server
        factory: ["@jfortunato_quick_books_desktop.factory.wrapper", "newUtilities"]
